repos:
  - repo: git://github.com/joker8023/pre-commit-golang
    rev: v1.10
    hooks:
      - id: go-fmt
        args:
          - --timeout=1000s
      - id: go-imports
      - id: golangci-lint
      - id: go-mod-tidy
