// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.18.0--rc1
// source: api/grpc/protos/privilege.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetUserPrivilegeAllParam struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Domain  string `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	SiteKey string `protobuf:"bytes,2,opt,name=siteKey,proto3" json:"siteKey,omitempty"`
}

func (x *GetUserPrivilegeAllParam) Reset() {
	*x = GetUserPrivilegeAllParam{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_protos_privilege_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserPrivilegeAllParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserPrivilegeAllParam) ProtoMessage() {}

func (x *GetUserPrivilegeAllParam) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_protos_privilege_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserPrivilegeAllParam.ProtoReflect.Descriptor instead.
func (*GetUserPrivilegeAllParam) Descriptor() ([]byte, []int) {
	return file_api_grpc_protos_privilege_proto_rawDescGZIP(), []int{0}
}

func (x *GetUserPrivilegeAllParam) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *GetUserPrivilegeAllParam) GetSiteKey() string {
	if x != nil {
		return x.SiteKey
	}
	return ""
}

type GetUserPrivilegeAllReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Privilege []*GetUserPrivilegeAllReply_Privilege `protobuf:"bytes,1,rep,name=privilege,proto3" json:"privilege,omitempty"`
}

func (x *GetUserPrivilegeAllReply) Reset() {
	*x = GetUserPrivilegeAllReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_protos_privilege_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserPrivilegeAllReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserPrivilegeAllReply) ProtoMessage() {}

func (x *GetUserPrivilegeAllReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_protos_privilege_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserPrivilegeAllReply.ProtoReflect.Descriptor instead.
func (*GetUserPrivilegeAllReply) Descriptor() ([]byte, []int) {
	return file_api_grpc_protos_privilege_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserPrivilegeAllReply) GetPrivilege() []*GetUserPrivilegeAllReply_Privilege {
	if x != nil {
		return x.Privilege
	}
	return nil
}

type GetUserPrivilegeAllReply_Privilege struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PrivilegeKey string `protobuf:"bytes,1,opt,name=privilege_key,json=privilegeKey,proto3" json:"privilege_key,omitempty"`
	Name         string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ParentKey    string `protobuf:"bytes,3,opt,name=parent_key,json=parentKey,proto3" json:"parent_key,omitempty"`
	Category     string `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	Shape        string `protobuf:"bytes,5,opt,name=shape,proto3" json:"shape,omitempty"`
	Point        string `protobuf:"bytes,6,opt,name=point,proto3" json:"point,omitempty"`
	Type         string `protobuf:"bytes,7,opt,name=type,proto3" json:"type,omitempty"`
	Icon         string `protobuf:"bytes,8,opt,name=icon,proto3" json:"icon,omitempty"`
	SortValue    int32  `protobuf:"varint,9,opt,name=sort_value,json=sortValue,proto3" json:"sort_value,omitempty"`
}

func (x *GetUserPrivilegeAllReply_Privilege) Reset() {
	*x = GetUserPrivilegeAllReply_Privilege{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_grpc_protos_privilege_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserPrivilegeAllReply_Privilege) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserPrivilegeAllReply_Privilege) ProtoMessage() {}

func (x *GetUserPrivilegeAllReply_Privilege) ProtoReflect() protoreflect.Message {
	mi := &file_api_grpc_protos_privilege_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserPrivilegeAllReply_Privilege.ProtoReflect.Descriptor instead.
func (*GetUserPrivilegeAllReply_Privilege) Descriptor() ([]byte, []int) {
	return file_api_grpc_protos_privilege_proto_rawDescGZIP(), []int{1, 0}
}

func (x *GetUserPrivilegeAllReply_Privilege) GetPrivilegeKey() string {
	if x != nil {
		return x.PrivilegeKey
	}
	return ""
}

func (x *GetUserPrivilegeAllReply_Privilege) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetUserPrivilegeAllReply_Privilege) GetParentKey() string {
	if x != nil {
		return x.ParentKey
	}
	return ""
}

func (x *GetUserPrivilegeAllReply_Privilege) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *GetUserPrivilegeAllReply_Privilege) GetShape() string {
	if x != nil {
		return x.Shape
	}
	return ""
}

func (x *GetUserPrivilegeAllReply_Privilege) GetPoint() string {
	if x != nil {
		return x.Point
	}
	return ""
}

func (x *GetUserPrivilegeAllReply_Privilege) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *GetUserPrivilegeAllReply_Privilege) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *GetUserPrivilegeAllReply_Privilege) GetSortValue() int32 {
	if x != nil {
		return x.SortValue
	}
	return 0
}

var File_api_grpc_protos_privilege_proto protoreflect.FileDescriptor

var file_api_grpc_protos_privilege_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x73, 0x2f, 0x70, 0x72, 0x69, 0x76, 0x69, 0x6c, 0x65, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x22, 0x4c, 0x0a, 0x18, 0x47, 0x65, 0x74,
	0x55, 0x73, 0x65, 0x72, 0x50, 0x72, 0x69, 0x76, 0x69, 0x6c, 0x65, 0x67, 0x65, 0x41, 0x6c, 0x6c,
	0x50, 0x61, 0x72, 0x61, 0x6d, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x12, 0x18, 0x0a,
	0x07, 0x73, 0x69, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x73, 0x69, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x22, 0xd9, 0x02, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x55,
	0x73, 0x65, 0x72, 0x50, 0x72, 0x69, 0x76, 0x69, 0x6c, 0x65, 0x67, 0x65, 0x41, 0x6c, 0x6c, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x48, 0x0a, 0x09, 0x70, 0x72, 0x69, 0x76, 0x69, 0x6c, 0x65, 0x67,
	0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73,
	0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x50, 0x72, 0x69, 0x76, 0x69, 0x6c, 0x65, 0x67,
	0x65, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x2e, 0x50, 0x72, 0x69, 0x76, 0x69, 0x6c,
	0x65, 0x67, 0x65, 0x52, 0x09, 0x70, 0x72, 0x69, 0x76, 0x69, 0x6c, 0x65, 0x67, 0x65, 0x1a, 0xf2,
	0x01, 0x0a, 0x09, 0x50, 0x72, 0x69, 0x76, 0x69, 0x6c, 0x65, 0x67, 0x65, 0x12, 0x23, 0x0a, 0x0d,
	0x70, 0x72, 0x69, 0x76, 0x69, 0x6c, 0x65, 0x67, 0x65, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0c, 0x70, 0x72, 0x69, 0x76, 0x69, 0x6c, 0x65, 0x67, 0x65, 0x4b, 0x65,
	0x79, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x5f,
	0x6b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x61, 0x72, 0x65, 0x6e,
	0x74, 0x4b, 0x65, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79,
	0x12, 0x14, 0x0a, 0x05, 0x73, 0x68, 0x61, 0x70, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x73, 0x68, 0x61, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x69, 0x63, 0x6f, 0x6e, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x69, 0x63, 0x6f, 0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x6f, 0x72, 0x74, 0x5f, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x73, 0x6f, 0x72, 0x74, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x32, 0x68, 0x0a, 0x09, 0x50, 0x72, 0x69, 0x76, 0x69, 0x6c, 0x65, 0x67, 0x65,
	0x12, 0x5b, 0x0a, 0x13, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x50, 0x72, 0x69, 0x76, 0x69,
	0x6c, 0x65, 0x67, 0x65, 0x41, 0x6c, 0x6c, 0x12, 0x20, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73,
	0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x50, 0x72, 0x69, 0x76, 0x69, 0x6c, 0x65, 0x67,
	0x65, 0x41, 0x6c, 0x6c, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x1a, 0x20, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x50, 0x72, 0x69, 0x76, 0x69, 0x6c,
	0x65, 0x67, 0x65, 0x41, 0x6c, 0x6c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x18, 0x5a,
	0x16, 0x61, 0x70, 0x69, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73,
	0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_grpc_protos_privilege_proto_rawDescOnce sync.Once
	file_api_grpc_protos_privilege_proto_rawDescData = file_api_grpc_protos_privilege_proto_rawDesc
)

func file_api_grpc_protos_privilege_proto_rawDescGZIP() []byte {
	file_api_grpc_protos_privilege_proto_rawDescOnce.Do(func() {
		file_api_grpc_protos_privilege_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_grpc_protos_privilege_proto_rawDescData)
	})
	return file_api_grpc_protos_privilege_proto_rawDescData
}

var file_api_grpc_protos_privilege_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_grpc_protos_privilege_proto_goTypes = []interface{}{
	(*GetUserPrivilegeAllParam)(nil),           // 0: protos.GetUserPrivilegeAllParam
	(*GetUserPrivilegeAllReply)(nil),           // 1: protos.GetUserPrivilegeAllReply
	(*GetUserPrivilegeAllReply_Privilege)(nil), // 2: protos.GetUserPrivilegeAllReply.Privilege
}
var file_api_grpc_protos_privilege_proto_depIdxs = []int32{
	2, // 0: protos.GetUserPrivilegeAllReply.privilege:type_name -> protos.GetUserPrivilegeAllReply.Privilege
	0, // 1: protos.Privilege.GetUserPrivilegeAll:input_type -> protos.GetUserPrivilegeAllParam
	1, // 2: protos.Privilege.GetUserPrivilegeAll:output_type -> protos.GetUserPrivilegeAllReply
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_grpc_protos_privilege_proto_init() }
func file_api_grpc_protos_privilege_proto_init() {
	if File_api_grpc_protos_privilege_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_grpc_protos_privilege_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserPrivilegeAllParam); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grpc_protos_privilege_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserPrivilegeAllReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_grpc_protos_privilege_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserPrivilegeAllReply_Privilege); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_grpc_protos_privilege_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_grpc_protos_privilege_proto_goTypes,
		DependencyIndexes: file_api_grpc_protos_privilege_proto_depIdxs,
		MessageInfos:      file_api_grpc_protos_privilege_proto_msgTypes,
	}.Build()
	File_api_grpc_protos_privilege_proto = out.File
	file_api_grpc_protos_privilege_proto_rawDesc = nil
	file_api_grpc_protos_privilege_proto_goTypes = nil
	file_api_grpc_protos_privilege_proto_depIdxs = nil
}
