// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// RoleClient is the client API for Role service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RoleClient interface {
	SetUserRole(ctx context.Context, in *SetUserRoleParam, opts ...grpc.CallOption) (*SetUserRoleReply, error)
	GetUserRole(ctx context.Context, in *GetUserRoleParam, opts ...grpc.CallOption) (*GetUserRoleReply, error)
	GetUserListByRoleKey(ctx context.Context, in *GetUserListByRoleKeyParam, opts ...grpc.CallOption) (*GetUserListByRoleKeyReply, error)
}

type roleClient struct {
	cc grpc.ClientConnInterface
}

func NewRoleClient(cc grpc.ClientConnInterface) RoleClient {
	return &roleClient{cc}
}

func (c *roleClient) SetUserRole(ctx context.Context, in *SetUserRoleParam, opts ...grpc.CallOption) (*SetUserRoleReply, error) {
	out := new(SetUserRoleReply)
	err := c.cc.Invoke(ctx, "/protos.Role/SetUserRole", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roleClient) GetUserRole(ctx context.Context, in *GetUserRoleParam, opts ...grpc.CallOption) (*GetUserRoleReply, error) {
	out := new(GetUserRoleReply)
	err := c.cc.Invoke(ctx, "/protos.Role/GetUserRole", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *roleClient) GetUserListByRoleKey(ctx context.Context, in *GetUserListByRoleKeyParam, opts ...grpc.CallOption) (*GetUserListByRoleKeyReply, error) {
	out := new(GetUserListByRoleKeyReply)
	err := c.cc.Invoke(ctx, "/protos.Role/GetUserListByRoleKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RoleServer is the server API for Role service.
// All implementations should embed UnimplementedRoleServer
// for forward compatibility
type RoleServer interface {
	SetUserRole(context.Context, *SetUserRoleParam) (*SetUserRoleReply, error)
	GetUserRole(context.Context, *GetUserRoleParam) (*GetUserRoleReply, error)
	GetUserListByRoleKey(context.Context, *GetUserListByRoleKeyParam) (*GetUserListByRoleKeyReply, error)
}

// UnimplementedRoleServer should be embedded to have forward compatible implementations.
type UnimplementedRoleServer struct {
}

func (UnimplementedRoleServer) SetUserRole(context.Context, *SetUserRoleParam) (*SetUserRoleReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetUserRole not implemented")
}
func (UnimplementedRoleServer) GetUserRole(context.Context, *GetUserRoleParam) (*GetUserRoleReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserRole not implemented")
}
func (UnimplementedRoleServer) GetUserListByRoleKey(context.Context, *GetUserListByRoleKeyParam) (*GetUserListByRoleKeyReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserListByRoleKey not implemented")
}

// UnsafeRoleServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RoleServer will
// result in compilation errors.
type UnsafeRoleServer interface {
	mustEmbedUnimplementedRoleServer()
}

func RegisterRoleServer(s grpc.ServiceRegistrar, srv RoleServer) {
	s.RegisterService(&Role_ServiceDesc, srv)
}

func _Role_SetUserRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetUserRoleParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoleServer).SetUserRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Role/SetUserRole",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoleServer).SetUserRole(ctx, req.(*SetUserRoleParam))
	}
	return interceptor(ctx, in, info, handler)
}

func _Role_GetUserRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRoleParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoleServer).GetUserRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Role/GetUserRole",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoleServer).GetUserRole(ctx, req.(*GetUserRoleParam))
	}
	return interceptor(ctx, in, info, handler)
}

func _Role_GetUserListByRoleKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserListByRoleKeyParam)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RoleServer).GetUserListByRoleKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protos.Role/GetUserListByRoleKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RoleServer).GetUserListByRoleKey(ctx, req.(*GetUserListByRoleKeyParam))
	}
	return interceptor(ctx, in, info, handler)
}

// Role_ServiceDesc is the grpc.ServiceDesc for Role service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Role_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protos.Role",
	HandlerType: (*RoleServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetUserRole",
			Handler:    _Role_SetUserRole_Handler,
		},
		{
			MethodName: "GetUserRole",
			Handler:    _Role_GetUserRole_Handler,
		},
		{
			MethodName: "GetUserListByRoleKey",
			Handler:    _Role_GetUserListByRoleKey_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/grpc/protos/role.proto",
}
